name: Build php_curl (Schannel)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout PHP-SDK
        uses: actions/checkout@v4
        with:
          repository: microsoft/php-sdk-binary-tools
          path: sdk

      - name: Prepare build tree
        run: |
          cd sdk
          .\bin\phpsdk_buildtree php-7.1 x64
          cd phpdev\vc15\x64
          git clone https://github.com/php/php-src.git
          cd php-src
          git checkout PHP-7.1.7
          ..\..\..\..\bin\phpsdk_deps --update
          buildconf

      - name: Configure (Schannel, NTS)
        run: |
          cd sdk\phpdev\vc15\x64\php-src
          configure ^
            --disable-all ^
            --enable-cli ^
            --enable-curl=shared ^
            --with-curl=schannel ^
            --enable-mbstring ^
            --enable-json ^
            --enable-session

      - name: Build
        run: |
          cd sdk\phpdev\vc15\x64\php-src
          nmake /nologo

      - name: Upload php_curl.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: php_curl_dll
          path: |
            sdk\phpdev\vc15\x64\php-7.1.7-nts-windows-vc14-x64\ext\php_curl.dll